<!--
SPDX-FileCopyrightText: 2022 ALAD SRL <info@alad.cloud>

SPDX-License-Identifier: MIT
-->

# ALAD0301

**Id**: ALAD0301\
**Titolo**: Log in un blocco catch senza eccezione\
**Categoria**: Logging\
**Gravità**: Warning

Si verifica quando in un blocco `catch` viene scritta una voce di log senza
i dettagli dell'eccezione.

I log devono loggare eventi ed essere trattati come scritture di record su un
database. Ciascuna scrittura deve contenere tutte le informazioni relative
all'evento loggato. Anche se l'eccezione non è particolarmente utile, può essere
una buona idea allegarla al log per agevolare eventuali analisi future.


## Esempio

```csharp
try {
  // qualcosa
} catch (Exception ex) {
  _logging.LogError("Errore elaborazione: {Message}", ex.Message); // ALAD0301
  throw;
}
```


## Soluzione

Aggiungere l'eccezione come primo parametro alla funzione di log.

```csharp
try {
  // qualcosa
} catch (Exception ex) {
  _logging.LogError(ex, "Errore elaborazione."); // OK
  throw;
}
```


## Analyzer

* [ALAD0301](../../src/Alad.CodeAnalyzer/Logging/LogWithoutExceptionAnalyzer.cs)


## Code-fix

Nessuna code-fix automatica disponibile.
